/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file cmd/image/create.c
 * @brief "ice image create" subcommand.
 *
 * Thin CLI wrapper around the @ref elf2image.h engine.  Parses the
 * esptool-compatible flag set, reads the input ELF, calls e2i_build,
 * and writes the generated image to disk.  Aliased as @c elf2image
 * for drop-in compatibility with @c esptool invocations.
 */
#include "elf2image.h"
#include "ice.h"

/* clang-format off */
static const struct cmd_manual image_create_manual = {
	.name = "ice image create",
	.summary = "create a flash image from an ELF executable",

	.description =
	H_PARA("Drop-in replacement for @b{esptool elf2image}.  Reads an "
	       "ELF executable produced by the IDF toolchain and writes "
	       "the corresponding ESP flash image.  Output is bootable "
	       "on the target chip's ROM bootloader.  Invocable as "
	       "@b{ice image create} or @b{ice image elf2image} "
	       "(compatibility alias).")
	H_PARA("@b{--chip} and @b{--flash-freq} are required; everything "
	       "else has sensible defaults or is silently accepted for "
	       "compatibility with @b{esptool}'s CLI (so invocations "
	       "generated by CMake can be rewritten from @b{esptool} "
	       "to @b{ice image} unchanged)."),

	.examples =
	H_EXAMPLE("ice image create --chip esp32 --flash-mode dio "
		  "--flash-freq 40m --flash-size 4MB "
		  "-o build/app.bin build/app.elf")
	H_EXAMPLE("ice image create --chip esp32c3 --flash-mode dio "
		  "--flash-freq 80m --flash-size 2MB "
		  "--elf-sha256-offset 0xb0 "
		  "-o build/app.bin build/app.elf"),

	.extras =
	H_SECTION("SEE ALSO")
	H_ITEM("ice build",
	       "Invokes this command automatically as part of the regular "
	       "build pipeline (via a build.ninja rewrite)."),
};
/* clang-format on */

/* File-scope so the option table is const and the completion backend
 * can walk it through cmd_image_create_opts. */
static const char *opt_chip;
static const char *opt_out;
static const char *opt_flash_mode = "dio";
static const char *opt_flash_freq; /* required */
static const char *opt_flash_size = "2MB";
static const char *opt_elf_sha256_offset; /* hex string */
static int opt_min_rev_full;
static int opt_max_rev_full = 0xFFFF;
static int opt_no_append_digest;

/* Esptool-compat flags we accept but do not (yet) act on. */
static const char *opt_pad_to_size;
static const char *opt_mmu_page_size;
static int opt_secure_pad;
static int opt_secure_pad_v2;
static int opt_use_segments;
static int opt_ram_only_header;
static int opt_min_rev_legacy;
static const char *opt_version;

static const struct option cmd_image_create_opts[] = {
    OPT_STRING(0, "chip", &opt_chip, "name",
	       "target chip (e.g. esp32, esp32s3, esp32c3)", NULL),
    OPT_STRING('o', NULL, &opt_out, "path", "output image path", NULL),
    OPT_STRING(0, "flash-mode", &opt_flash_mode, "mode",
	       "qio | qout | dio | dout (default dio)", NULL),
    OPT_STRING(0, "flash-freq", &opt_flash_freq, "freq",
	       "flash clock, chip-specific (e.g. 80m, 40m, 20m)", NULL),
    OPT_STRING(0, "flash-size", &opt_flash_size, "size",
	       "1MB | 2MB | 4MB | 8MB | 16MB | ...  (default 2MB)", NULL),
    OPT_STRING(0, "elf-sha256-offset", &opt_elf_sha256_offset, "hex",
	       "patch ELF SHA-256 at this absolute image offset", NULL),
    OPT_INT(0, "min-rev-full", &opt_min_rev_full, "n",
	    "minimum chip revision (full form)", NULL),
    OPT_INT(0, "max-rev-full", &opt_max_rev_full, "n",
	    "maximum chip revision (full form)", NULL),
    OPT_BOOL(0, "no-append-digest", &opt_no_append_digest,
	     "do not append the 32-byte SHA-256 digest"),

    /* Accepted for esptool CLI compatibility; see comments in body. */
    OPT_STRING(0, "pad-to-size", &opt_pad_to_size, "size",
	       "pad output to this flash size with 0xFF", NULL),
    OPT_STRING(0, "flash-mmu-page-size", &opt_mmu_page_size, "size",
	       "(accepted, only 64KB is implemented today)", NULL),
    OPT_BOOL(0, "secure-pad", &opt_secure_pad,
	     "(accepted, no-op in this release)"),
    OPT_BOOL(0, "secure-pad-v2", &opt_secure_pad_v2,
	     "(accepted, no-op in this release)"),
    OPT_BOOL(0, "use-segments", &opt_use_segments,
	     "(accepted; segments are always used)"),
    OPT_BOOL(0, "ram-only-header", &opt_ram_only_header,
	     "(accepted, no-op in this release)"),
    OPT_INT(0, "min-rev", &opt_min_rev_legacy, "n",
	    "deprecated; use --min-rev-full", NULL),
    OPT_STRING(0, "version", &opt_version, "N",
	       "ESP8266 image version (ESP8266 is not supported)", NULL),
    OPT_END(),
};

int cmd_image_create(int argc, const char **argv);

const struct cmd_desc cmd_image_create_desc = {
    .name = "create",
    .fn = cmd_image_create,
    .opts = cmd_image_create_opts,
    .manual = &image_create_manual,
};

static uint32_t parse_hex(const char *s, const char *flag)
{
	char *end;
	unsigned long v;

	errno = 0;
	v = strtoul(s, &end, 0);
	if (errno != 0 || *end != '\0')
		die("invalid %s value '%s'", flag, s);
	return (uint32_t)v;
}

static void pad_to(struct sbuf *sb, size_t target)
{
	if (sb->len >= target)
		return;
	size_t n = target - sb->len;

	sbuf_grow(sb, n);
	memset(sb->buf + sb->len, 0xFF, n);
	sbuf_setlen(sb, sb->len + n);
}

/* Parse an IDF-style flash-size string ("4MB", "1MB") into bytes.
 * Used only for --pad-to-size; the main --flash-size value is forwarded
 * as a string to e2i_build. */
static size_t flash_size_bytes(const char *s)
{
	char *end;
	unsigned long mb;

	errno = 0;
	mb = strtoul(s, &end, 10);
	if (errno != 0 || end == s || strcmp(end, "MB") != 0) {
		/* Also accept sub-MB for bootloader pad-to-size (4KB). */
		if (strcmp(s, "4KB") == 0)
			return (size_t)4u * (size_t)1024u;
		die("unrecognised flash size '%s' (expected e.g. 2MB or 4KB)",
		    s);
	}
	return (size_t)mb * (size_t)1024u * (size_t)1024u;
}

int cmd_image_create(int argc, const char **argv)
{
	struct sbuf elf = SBUF_INIT;
	struct sbuf img = SBUF_INIT;
	FILE *fp;

	argc = parse_options(argc, argv, &cmd_image_create_desc);

	if (argc < 1)
		die("missing input ELF path");
	if (argc > 1)
		die("too many positional arguments");
	if (!opt_chip)
		die("--chip is required");
	if (!opt_out)
		die("-o <output.bin> is required");
	if (!opt_flash_freq)
		die("--flash-freq is required");

	enum bin_chip chip = bin_chip_by_name(opt_chip);

	if (chip == BIN_CHIP_MAX) {
		struct sbuf names = SBUF_INIT;
		for (const char *const *n = bin_chip_names(); *n; n++) {
			if (names.len > 0)
				sbuf_addstr(&names, ", ");
			sbuf_addstr(&names, *n);
		}
		die("unsupported --chip '%s' (supported: %s)", opt_chip,
		    names.buf);
	}

	if (opt_ram_only_header || opt_secure_pad || opt_secure_pad_v2)
		warn("ignoring unsupported esptool option (PoC limitation)");
	if (opt_version)
		warn("--version is ESP8266-only and ESP8266 is not supported");

	/*
	 * Only 64 KB MMU page size is implemented; warn if the caller
	 * asked for something different so we do not silently miscompile.
	 */
	if (opt_mmu_page_size && strcmp(opt_mmu_page_size, "64KB") != 0)
		warn("--flash-mmu-page-size %s is not implemented; "
		     "using 64KB",
		     opt_mmu_page_size);

	const char *elf_path = argv[0];

	if (sbuf_read_file(&elf, elf_path) < 0)
		die_errno("cannot read '%s'", elf_path);

	struct e2i_config cfg = E2I_CONFIG_DEFAULT();
	cfg.flash_mode = opt_flash_mode;
	cfg.flash_freq = opt_flash_freq;
	cfg.flash_size = opt_flash_size;
	cfg.min_rev_full = (uint16_t)opt_min_rev_full;
	cfg.max_rev_full = (uint16_t)opt_max_rev_full;
	cfg.append_sha256 = !opt_no_append_digest;
	cfg.elf_sha256_offset =
	    opt_elf_sha256_offset
		? parse_hex(opt_elf_sha256_offset, "--elf-sha256-offset")
		: 0u;

	e2i_build(elf.buf, elf.len, chip, &cfg, &img);

	if (opt_pad_to_size) {
		size_t target = flash_size_bytes(opt_pad_to_size);
		pad_to(&img, target);
	}

	mkdirp_for_file(opt_out);

	fp = fopen(opt_out, "wb");
	if (!fp)
		die_errno("cannot write '%s'", opt_out);
	if (fwrite(img.buf, 1, img.len, fp) != img.len) {
		fclose(fp);
		die_errno("write error on '%s'", opt_out);
	}
	fclose(fp);

	sbuf_release(&img);
	sbuf_release(&elf);
	return 0;
}
