/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file cmd/partition-table/partition-table.c
 * @brief "ice idf partition-table" subcommand.
 */
#include "ice.h"
#include "partition_table.h"

/* clang-format off */
static const struct cmd_manual partition_table_manual = {
	.name = "ice idf partition-table",
	.summary = "generate partition table binary from CSV",

	.description =
	H_PARA("Drop-in replacement for ESP-IDF's @b{gen_esp32part.py}.  "
	       "Reads a partition table in the IDF CSV dialect and writes "
	       "the corresponding binary image (3 KB of 32-byte entries "
	       "plus the MD5 sentinel, 0xFF-padded).")
	H_PARA("Accepts the same flags that IDF's @b{partition_table} cmake "
	       "component passes to @b{gen_esp32part.py}, so invocations "
	       "generated by cmake can be rewritten to call @b{ice "
	       "partition-table} unchanged.  @b{ice build} performs that "
	       "rewrite automatically during configure.")
	H_PARA("CSV dialect: one partition per line, fields "
	       "@b{Name,Type,SubType,Offset,Size,Flags}; K / M size "
	       "suffixes, hex offsets, @b{ota_N} / @b{tee_N} app subtypes, "
	       "and a leading @b{-} on the Size field (\"fill to this "
	       "address\") are all supported.  Lines starting with @b{#} "
	       "are comments; blank lines are ignored.  Missing offsets are "
	       "auto-filled using IDF's alignment rules (0x10000 for app, "
	       "0x1000 otherwise)."),

	.examples =
	H_EXAMPLE("ice idf partition-table partitions.csv build/partition-table.bin")
	H_EXAMPLE("ice idf partition-table --flash-size 4MB partitions.csv build/pt.bin")
	H_EXAMPLE("ice idf partition-table --disable-md5sum partitions.csv out.bin"),

	.extras =
	H_SECTION("SEE ALSO")
	H_ITEM("ice build",
	       "Invokes this command automatically as part of the regular "
	       "build pipeline; usually the way end users reach it."),
};
/* clang-format on */

/*
 * File-scope so the completion backend can walk the option table via
 * cmd_struct.opts.  Defaults live on the variables; parse_options
 * overwrites them when flags are passed.
 */
static const char *offset_str = "0x8000";
static const char *pbl_offset_str;
static const char *rbl_offset_str;
static const char *flash_size_str;
static const char *secure_str;
static int disable_md5;
static int no_verify;
static int quiet;
/* --extra-partition-subtypes: accepted, ignored (numeric always works). */
static const char *extra_subtypes;

static const struct option cmd_partition_table_opts[] = {
    OPT_BOOL('q', "quiet", &quiet, "suppress non-error output"),
    OPT_STRING(0, "offset", &offset_str, "hex",
	       "partition table offset in flash (default 0x8000)", NULL),
    OPT_STRING(0, "primary-bootloader-offset", &pbl_offset_str, "hex",
	       "primary bootloader offset in flash", NULL),
    OPT_STRING(0, "recovery-bootloader-offset", &rbl_offset_str, "hex",
	       "recovery bootloader offset in flash", NULL),
    OPT_BOOL(0, "disable-md5sum", &disable_md5, "disable MD5 checksum entry"),
    OPT_BOOL(0, "no-verify", &no_verify, "skip partition table validation"),
    OPT_STRING(0, "flash-size", &flash_size_str, "NMB",
	       "flash size for validation (e.g. 4MB)", NULL),
    OPT_STRING(0, "secure", &secure_str, "v1|v2", "secure boot version", NULL),
    OPT_STRING(0, "extra-partition-subtypes", &extra_subtypes, "...",
	       "extra subtype definitions (ignored)", NULL),
    OPT_END(),
};

const struct cmd_desc cmd_partition_table_desc = {
    .name = "partition-table",
    .fn = cmd_partition_table,
    .opts = cmd_partition_table_opts,
    .manual = &partition_table_manual,
};

int cmd_partition_table(int argc, const char **argv)
{
	struct pt_options pt_opts;
	struct pt_entry entries[PT_MAX_ENTRIES];
	uint8_t binary[PT_DATA_SIZE];
	int count = 0;
	const char *input_path;
	const char *output_path;
	FILE *fp;

	argc = parse_options(argc, argv, &cmd_partition_table_desc);

	if (argc < 2)
		die("usage: ice idf partition-table [options] <input.csv> "
		    "<output.bin>");

	input_path = argv[0];
	output_path = argv[1];

	/* Build options struct */
	memset(&pt_opts, 0, sizeof(pt_opts));
	pt_opts.md5sum = !disable_md5;

	/* --offset */
	{
		uint32_t v;
		char *end;
		v = (uint32_t)strtoul(offset_str, &end, 0);
		if (*end)
			die("invalid --offset value: %s", offset_str);
		pt_opts.table_offset = v;
	}

	/* --primary-bootloader-offset */
	if (pbl_offset_str) {
		char *end;
		pt_opts.primary_boot_offset =
		    (uint32_t)strtoul(pbl_offset_str, &end, 0);
		if (*end)
			die("invalid --primary-bootloader-offset: %s",
			    pbl_offset_str);
		pt_opts.has_primary_boot = 1;
	}

	/* --recovery-bootloader-offset */
	if (rbl_offset_str) {
		char *end;
		pt_opts.recovery_boot_offset =
		    (uint32_t)strtoul(rbl_offset_str, &end, 0);
		if (*end)
			die("invalid --recovery-bootloader-offset: %s",
			    rbl_offset_str);
		pt_opts.has_recovery_boot = 1;
	}

	/* --flash-size: strictly "<decimal>MB", matches gen_esp32part.py. */
	if (flash_size_str) {
		char *end;
		uint32_t mb = (uint32_t)strtoul(flash_size_str, &end, 10);
		if (end == flash_size_str || strcmp(end, "MB") != 0)
			die("invalid --flash-size '%s'; expected NMB (e.g. "
			    "4MB)",
			    flash_size_str);
		pt_opts.flash_size = mb * 1024 * 1024;
	}

	/* --secure */
	if (secure_str) {
		if (!strcmp(secure_str, "v1"))
			pt_opts.secure = PT_SECURE_V1;
		else if (!strcmp(secure_str, "v2"))
			pt_opts.secure = PT_SECURE_V2;
		else
			die("invalid --secure value: %s (use v1 or v2)",
			    secure_str);
	}

	/* Parse CSV */
	if (pt_parse_csv(input_path, entries, &count, &pt_opts) != 0)
		return 1;

	/* Validate (unless --no-verify) */
	if (!no_verify && count == 0) {
		err("empty partition table");
		return 1;
	}

	/* Print table to stderr (unless -q) */
	if (!quiet) {
		fprintf(stderr, "Partition table:\n");
		fprintf(stderr, "%-16s %-12s %-12s %-10s %-10s %s\n", "Name",
			"Type", "SubType", "Offset", "Size", "Flags");
		for (int i = 0; i < count; i++) {
			const struct pt_entry *e = &entries[i];
			fprintf(stderr,
				"%-16s 0x%02x         0x%02x         "
				"0x%08x 0x%08x %s%s\n",
				e->name, e->type, e->subtype, e->offset,
				e->size, e->encrypted ? "encrypted " : "",
				e->readonly ? "readonly" : "");
		}
	}

	/* Serialise */
	if (pt_to_binary(entries, count, &pt_opts, binary) != 0)
		return 1;

	/* Create output directory */
	mkdirp_for_file(output_path);

	/* Write output */
	fp = fopen(output_path, "wb");
	if (!fp) {
		err_errno("cannot write '%s'", output_path);
		return 1;
	}
	if (fwrite(binary, 1, PT_DATA_SIZE, fp) != PT_DATA_SIZE) {
		err_errno("write error on '%s'", output_path);
		fclose(fp);
		return 1;
	}
	fclose(fp);

	return 0;
}
