/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file cmd/completion/completion.c
 * @brief Shell completion support.
 *
 * Two subcommands live here:
 *
 *   ice completion bash|zsh|fish|powershell
 *     Public.  Prints a tiny shell-specific init snippet on stdout,
 *     meant to be evaluated from the user's rc file:
 *
 *         eval "$(ice completion bash)"       # ~/.bashrc
 *         eval "$(ice completion zsh)"        # ~/.zshrc
 *         ice completion fish | source        # fish
 *         ice completion powershell | Out-String | Invoke-Expression
 *
 *     The snippet binds a dispatch function to the `ice` command that
 *     re-invokes the hidden __complete backend on every TAB.
 *
 *   ice __complete <cword> <word>...
 *     Hidden.  Transforms the partial command line into a call to
 *     cmd_ice() with --ice-complete appended.  The normal dispatch
 *     chain routes to the deepest handler, whose parse_options()
 *     sees --ice-complete and prints candidates to stdout before
 *     exiting.  The shell captures the output.
 */
#include "ice.h"

/* ---- public: `ice completion <shell>` ------------------------------ */

/* clang-format off */
static const char bash_script[] =
	"# ice bash completion (install: eval \"$(ice completion bash)\")\n"
	"_ice_complete() {\n"
	"    local IFS=$'\\n'\n"
	"    local cur=\"${COMP_WORDS[COMP_CWORD]}\"\n"
	"    COMPREPLY=( $(compgen -W \"$(ice __complete \"$COMP_CWORD\" \"${COMP_WORDS[@]}\" 2>/dev/null)\" -- \"$cur\") )\n"
	"}\n"
	"complete -o default -o nosort -F _ice_complete ice\n";

static const char zsh_script[] =
	"# ice zsh completion (install: eval \"$(ice completion zsh)\")\n"
	"(( $+functions[compdef] )) || { autoload -Uz compinit && compinit -u; }\n"
	"_ice() {\n"
	"    local -a candidates\n"
	"    local IFS=$'\\n'\n"
	"    candidates=( ${(f)\"$(ice __complete $((CURRENT - 1)) \"${words[@]}\" 2>/dev/null)\"} )\n"
	"    if (( ${#candidates} )); then\n"
	"        compadd -V ice -a candidates\n"
	"    else\n"
	"        _files\n"
	"    fi\n"
	"}\n"
	"compdef _ice ice\n";

static const char fish_script[] =
	"# ice fish completion (install: ice completion fish | source)\n"
	"function __ice_complete\n"
	"    set -l words (commandline -opc) (commandline -ct)\n"
	"    ice __complete (math (count $words) - 1) $words 2>/dev/null\n"
	"end\n"
	"complete -c ice -f -k -a '(__ice_complete)'\n";

static const char powershell_script[] =
	"# ice PowerShell completion\n"
	"# install: ice completion powershell | Out-String | Invoke-Expression\n"
	"Register-ArgumentCompleter -Native -CommandName 'ice' -ScriptBlock {\n"
	"    param($wordToComplete, $commandAst, $cursorPosition)\n"
	"\n"
	"    $words = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })\n"
	"    if ($wordToComplete -eq '') { $words += '' }\n"
	"    $cword = $words.Count - 1\n"
	"\n"
	"    $results = @(& ice __complete $cword @words 2>$null |\n"
	"        Where-Object { $_ -and $_.StartsWith($wordToComplete) })\n"
	"    if ($results.Count -gt 0) {\n"
	"        $results | ForEach-Object {\n"
	"            [System.Management.Automation.CompletionResult]::new(\n"
	"                $_, $_, 'ParameterValue', $_)\n"
	"        }\n"
	"    } else {\n"
	"        Get-ChildItem -Path \"$wordToComplete*\" -ErrorAction SilentlyContinue |\n"
	"            ForEach-Object {\n"
	"                [System.Management.Automation.CompletionResult]::new(\n"
	"                    $_.Name, $_.Name, 'ProviderItem', $_.FullName)\n"
	"            }\n"
	"    }\n"
	"}\n";

static const struct cmd_manual completion_manual = {
	.name = "ice completion",
	.summary = "print shell completion script",

	.description =
	H_PARA("Emits a shell-specific completion script on standard "
	       "output, meant to be evaluated from the user's rc file.  "
	       "The script registers a dispatch function that calls a "
	       "hidden @b{ice __complete} backend on every @b{TAB}, so "
	       "candidates -- subcommands, long / short flags, aliases, "
	       "config keys, chip targets -- are always generated by the "
	       "current binary and cannot drift from available features.")
	H_PARA("The protocol is minimal: the shell glue forwards the word "
	       "array and cursor index to @b{ice __complete}, which prints "
	       "newline-separated candidates filtered by the current "
	       "prefix.  No on-disk completion file, no installation step."),

	.examples =
	H_EXAMPLE("eval \"$(ice completion bash)\"    # ~/.bashrc")
	H_EXAMPLE("eval \"$(ice completion zsh)\"     # ~/.zshrc")
	H_EXAMPLE("ice completion fish | source       # fish")
	H_EXAMPLE("ice completion powershell | Out-String | Invoke-Expression   # $PROFILE"),

	.extras =
	H_SECTION("SUPPORTED SHELLS")
	H_ITEM("bash",
	       "Binds via @b{complete -F}.  Falls through to filename "
	       "completion via @b{-o default} when the backend produces no "
	       "candidates.")
	H_ITEM("zsh",
	       "Binds via @b{compdef}.  Falls through to @b{_files} when "
	       "no candidates are produced.")
	H_ITEM("fish",
	       "Binds via @b{complete -c ice -f -a}.  Re-invokes the "
	       "backend each @b{TAB}.")
	H_ITEM("powershell",
	       "Binds via @b{Register-ArgumentCompleter -Native}.  Falls "
	       "back to @b{Get-ChildItem} for filename completion when the "
	       "backend produces no candidates.  Works in Windows PowerShell "
	       "5.1 and PowerShell 7+."),
};
/* clang-format on */

static void complete_shells(void) { printf("bash\nzsh\nfish\npowershell\n"); }

static const struct option cmd_completion_opts[] = {
    OPT_POSITIONAL("shell", complete_shells),
    OPT_END(),
};

const struct cmd_desc cmd_completion_desc = {
    .name = "completion",
    .fn = cmd_completion,
    .opts = cmd_completion_opts,
    .manual = &completion_manual,
};

int cmd_completion(int argc, const char **argv)
{
	argc = parse_options(argc, argv, &cmd_completion_desc);
	if (argc != 1)
		die("usage: ice completion bash|zsh|fish|powershell");

	if (!strcmp(argv[0], "bash"))
		fputs(bash_script, stdout);
	else if (!strcmp(argv[0], "zsh"))
		fputs(zsh_script, stdout);
	else if (!strcmp(argv[0], "fish"))
		fputs(fish_script, stdout);
	else if (!strcmp(argv[0], "powershell"))
		fputs(powershell_script, stdout);
	else
		die("unknown shell '%s' (supported: bash, zsh, fish, "
		    "powershell)",
		    argv[0]);
	return EXIT_SUCCESS;
}

/* ---- hidden: `ice __complete <cword> <word>...` -------------------- */

static const struct cmd_manual complete_manual = {.name = "ice __complete"};
static const struct option cmd___complete_opts[] = {OPT_END()};

const struct cmd_desc cmd___complete_desc = {
    .name = "__complete",
    .fn = cmd_complete,
    .opts = cmd___complete_opts,
    .manual = &complete_manual,
};

/**
 * Transform the partial command line into a cmd_ice() call with
 * --ice-complete appended.
 *
 * argv layout:  ["__complete", "<cword>", "ice", "target", "set", "es"]
 *
 * We take words[0..cword-1] (the resolved context before the cursor
 * word), append "--ice-complete", and call cmd_ice().  The normal
 * dispatch chain routes through subcommands until the deepest
 * parse_options() sees --ice-complete, dumps candidates, and exits.
 * The shell does prefix filtering.
 */
int cmd_complete(int argc, const char **argv)
{
	struct svec av = SVEC_INIT;
	int cword;
	int nwords;
	const char **words;

	/* argv[0]="__complete", argv[1]=cword, argv[2..]=words. */
	if (argc < 3)
		return EXIT_SUCCESS;

	cword = atoi(argv[1]);
	nwords = argc - 2;
	words = argv + 2;

	if (cword < 0 || cword >= nwords)
		return EXIT_SUCCESS;

	/* Build argv: words[0..cword-1] + "--ice-complete". */
	for (int i = 0; i < cword; i++)
		svec_push(&av, words[i]);
	svec_push(&av, "--ice-complete");

	cmd_ice((int)av.nr, (const char **)av.v);

	/* cmd_ice -> ... -> parse_options -> exit(0); normally unreached. */
	svec_clear(&av);
	return EXIT_SUCCESS;
}
